packages:
  - "packages/*"
catalog:
  "typescript": "5.8.3"
  "vite": "6.3.5"
  "vitest": "3.1.3"
  "@biomejs/biome": "1.9.4"
  "tsup": "8.4.0"
  "react": "19.1.0"
  "react-dom": "19.1.0"
  "@tailwindcss/vite": "^4.1.7"
  "tailwindcss": "^4.1.7"
  "react-use": "^17.6.0"
