defaults: &defaults
  docker:
    - image: google/cloud-sdk:latest

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: dependency-install
          command: yarn install --dev
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir ./test_report
      - run:
          name: test
          command: yarn test
      - store_test_results:
          path: ./test_report
      - store_artifacts:
          path: ./test_report

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    <<: *defaults
    working_directory: ~/turnament/packages/turnament-web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to GAE
          command: |
            pwd 
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud app deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - test #to forece correct order
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - build
